version = 1
SPDX-PackageName = "@schurteb/cloud-resume-challenge"
SPDX-PackageSupplier = "Benjamin Schurtenberger"
SPDX-PackageDownloadLocation = "https://github.com/schurteb/cloud-resume-challenge"
annotations = []
